// ✏️ Edit this file to update the portfolio content.
window.PORTFOLIO = {
  name: "Khushal Narsaria",
  short: "khushal",
  role: "Full-Stack Software Development Engineer",
  status: "Open to SDE roles · 2027 graduate",
  roles: ["Full-Stack Software Engineer", "Backend & Data Systems", "AI Agent Builder"],
  tagline:
    "I build full-stack products and reliable backend systems — REST APIs with idempotency and retries, well-indexed SQL, and clean Next.js frontends.",
  links: {
    github: "https://github.com/Khushal-Narsaria",
    linkedin: "https://www.linkedin.com/in/khushal-narsaria/",
    email: "khushalnarsaria@gmail.com",
  },
  terminal: {
    name: "Khushal Narsaria",
    role: "SDE · Full-Stack",
    stack: "Next.js · Node · .NET · SQL",
    cloud: "AWS · Docker · Kubernetes",
    based: "Chennai, India",
  },
  stats: [
    { value: "40%", label: "faster queries on hot tables" },
    { value: "8.81", label: "CGPA at SRM IST" },
    { value: "2nd", label: "place · Codefest Hackathon" },
    { value: "10+", label: "industry certifications" },
  ],
  about: [
    "I'm a <strong>Full-stack Software Development Engineer</strong> pursuing a B.Tech in Computer Science (AI &amp; ML) at SRM Institute of Science and Technology, graduating in 2027.",
    "As a Data Engineering intern at <strong>Emoolar Technology</strong>, I built backend data pipelines and optimized PostgreSQL with indexing and normalization, improving query efficiency by 40%.",
    "I build with <strong>Next.js, React, Node.js, Tailwind CSS and SQL</strong>, plus Spring Boot, FastAPI and .NET — with AWS, Docker, Kubernetes and CI/CD. I care about data integrity and reliable systems.",
  ],
  facts: [
    { icon: "pin", label: "Location", value: "Chennai, India" },
    { icon: "cap", label: "Education", value: "B.Tech CSE (AI & ML) · CGPA 8.81" },
    { icon: "brief", label: "Latest role", value: "Data Engineering Intern · Emoolar" },
    { icon: "star", label: "Achievement", value: "Codefest Hackathon — 2nd Place" },
  ],
  experience: [
    {
      title: "Data Engineering Intern",
      company: "Emoolar Technology Pvt Ltd",
      date: "May 2025 – Jul 2025",
      place: "Remote",
      points: [
        "Built backend data pipelines and automation scripts in Python and C++ to transform, migrate and validate structured datasets, ensuring data integrity for downstream services.",
        "Optimized PostgreSQL database structures using indexing and normalization, improving query execution efficiency by 40% on high-traffic tables.",
        "Worked in a 5-person agile team using Git and Jira to debug integration issues and document technical changes, supporting on-time delivery.",
      ],
      tags: ["Python", "C++", "PostgreSQL", "Git", "Jira"],
    },
  ],
  projects: [
    {
      title: "Retail Intelligence Platform",
      subtitle: "SQL warehouse, stock simulation and API",
      category: "Data",
      glyph: "£",
      colors: ["#2a78d6", "#1baf7a"],
      metric: { value: "1.07M", label: "real retail transactions · 2-member team" },
      points: [
        "DuckDB warehouse (staging, star schema, marts) over two years of a UK online retailer's orders.",
        "12 automated data-quality checks; 22,523 duplicated source rows found and removed.",
        "Stock simulation for 791 products: 5.9% less stock at a 90% fill rate with the model forecast.",
        "FastAPI service over the warehouse; 21 tests in CI and a live dashboard.",
      ],
      tags: ["Python", "SQL", "DuckDB", "scikit-learn", "FastAPI"],
      github: "https://github.com/S-Harshni/Retail-Intelligence-Platform",
      live: "https://s-harshni.github.io/Retail-Intelligence-Platform/",
    },
    {
      title: "Procurement Analytics & Supplier Scorecard",
      subtitle: "Spend, suppliers, savings and reorder policy",
      category: "Data",
      glyph: "₹",
      colors: ["#0f6b52", "#c98a12"],
      metric: { value: "40%", label: "lower ordering + holding cost in a simulated backtest" },
      points: [
        "Spend analysis (Pareto, ABC) and a weighted supplier scorecard, with metrics written in SQL.",
        "Runs on simulated data: 8,791 purchase-order lines, 40 suppliers, 120 materials.",
        "Safety stock, reorder point and EOQ per material; policy held 50% less stock at a 99.4% fill rate.",
        "Scorecard validated against hidden supplier behaviour; 9 tests in CI and a live dashboard.",
      ],
      tags: ["Python", "SQL", "pandas", "Supply chain", "Chart.js"],
      github: "https://github.com/Khushal-Narsaria/Procurement-Analytics-Supplier-Scorecard",
      live: "https://khushal-narsaria.github.io/Procurement-Analytics-Supplier-Scorecard/",
    },
    {
      title: "DSP Toolkit & Spectrum Analyzer",
      subtitle: "Signal processing library + interactive lab",
      category: "DSP",
      glyph: "∿",
      colors: ["#4f46e5", "#0891b2"],
      metric: { value: "34", label: "unit tests against theory" },
      points: [
        "Radix-2 FFT, windowed-sinc FIR design, decimation & interpolation, correlation.",
        "AM/FM, ASK, BPSK and 16-QAM with Monte-Carlo BER vs theory.",
        "FFT and swept-tuned spectrum analyzers, accurate to 0.1 dB.",
        "C++17 core, MATLAB reference and an in-browser lab.",
      ],
      tags: ["C++17", "MATLAB", "FFT", "FIR", "Modulation"],
      github: "https://github.com/Khushal-Narsaria/DSP-Toolkit-Spectrum-Analyzer",
      live: "https://khushal-narsaria.github.io/DSP-Toolkit-Spectrum-Analyzer/",
    },
    {
      title: "GoCart",
      subtitle: "Full-stack e-commerce platform",
      category: "Full-Stack",
      glyph: "{ }",
      colors: ["#2f6fed", "#7c3aed"],
      metric: { value: "50%", label: "faster joins via indexing" },
      points: [
        "Store with product browsing, cart and checkout using Next.js, Tailwind and Redux Toolkit.",
        "REST APIs on Next.js routes with idempotency and retry logic, handling 100+ daily transactions.",
        "Prisma schema and migrations on PostgreSQL/MySQL.",
        "NextAuth login, user dashboard and admin panel for products, users and orders.",
      ],
      tags: ["Next.js", "Node.js", "Tailwind", "Redux", "Prisma", "SQL"],
      github: "https://github.com/Khushal-Narsaria/GoCart-Fullstack-E-Commerce-Website",
      live: "https://khushal-narsaria.github.io/GoCart-Fullstack-E-Commerce-Website/",
    },
    {
      title: "Inventory & Order Management",
      subtitle: "Warehouse and order system",
      category: "Full-Stack",
      glyph: "#",
      colors: ["#4f46e5", "#0ea5e9"],
      metric: { value: "CQRS", label: "Clean Architecture · .NET 9" },
      points: [
        "ASP.NET Core 9 Web API with Clean Architecture, CQRS (MediatR) and Repository pattern.",
        "Sales, purchase and warehouse modules: orders, returns, goods receipt, transfers, stock counts.",
        "ASP.NET Identity + JWT with role-based access; FluentValidation and Serilog.",
        "Vue.js + Razor Pages UI with stock and movement reports on SQL Server.",
      ],
      tags: ["ASP.NET Core", "C#", "EF Core", "SQL Server", "Vue.js"],
      github: "https://github.com/Khushal-Narsaria/Inventory-Order-Management-System",
      live: "https://khushal-narsaria.github.io/Inventory-Order-Management-System/",
    },
    {
      title: "Meeting Assistant Agent",
      subtitle: "AI agent for meeting notes → tasks",
      category: "AI / ML",
      glyph: "AI",
      colors: ["#0fb5a6", "#2563eb"],
      metric: { value: "10K+", label: "transcripts · 95% accuracy" },
      points: [
        "Agno framework + LLMs (Nebius API) turn meeting notes into clean summaries.",
        "Linear API integration auto-creates tasks from action items.",
        "Slack bot posts key decisions and next steps to team channels.",
        "Streamlit UI with chat input.",
      ],
      tags: ["Python", "Agno", "LLMs", "Linear API", "Slack API", "Streamlit"],
      github: "https://github.com/Khushal-Narsaria/meeting_assistant_agent",
    },
    {
      title: "Fashion Recommendation System",
      subtitle: "Deep-learning visual recommendations",
      category: "AI / ML",
      glyph: "◎",
      colors: ["#db2777", "#f59e0b"],
      metric: { value: "92%", label: "top-5 accuracy" },
      points: [
        "ResNet classifier in TensorFlow on DeepFashion (289K+ images, 50 categories, 1,000 attributes).",
        "Modular pipeline: preprocessing, image processing, hyperparameter config, train/test scripts.",
        "Nearest-neighbor recommendations on CNN embeddings, cutting retrieval latency by 40%.",
      ],
      tags: ["Python", "TensorFlow", "ResNet", "k-NN"],
      github: "https://github.com/Khushal-Narsaria/Fashion-Recommendation-System",
      live: "https://khushal-narsaria.github.io/Fashion-Recommendation-System/",
    },
  ],
  skills: {
    Languages: ["JavaScript", "Python", "Java", "C#", "C++", "SQL / T-SQL"],
    Frontend: ["React.js", "Next.js", "Vue.js", "Tailwind CSS", "Redux Toolkit"],
    Backend: ["Node.js", "ASP.NET Core", "Spring Boot", "FastAPI", "REST API Design", "Prisma ORM"],
    Databases: ["MySQL", "PostgreSQL", "MongoDB", "SQL Server", "Redis", "Indexing & Normalization"],
    "Cloud & DevOps": ["AWS", "Docker", "Kubernetes", "GitHub Actions", "Linux", "Nginx", "Kafka"],
    "Tools & AI": ["Git", "Jira", "PyTorch", "Hugging Face", "LangChain", "RAG"],
  },
  education: [
    {
      school: "SRM Institute of Science and Technology",
      date: "2023 – 2027",
      degree: "B.Tech, Computer Science & Engineering (AI & ML) · Kattankulathur, Chennai",
      score: "CGPA 8.81 / 10",
      coursework:
        "DSA · Design & Analysis of Algorithms · DBMS · OOP · Operating Systems · Computer Networks · Software Engineering",
    },
    {
      school: "Sri Chaitanya Jr College",
      date: "2021 – 2023",
      degree: "Class XII, MPC · Visakhapatnam, Andhra Pradesh",
      score: "81.2%",
    },
  ],
  certsTitle: "Certifications & Achievements",
  certs: [
    "Codefest Technical Hackathon — 2nd Place, SRM IST",
    "AWS Certified Developer – Associate",
    "Meta Back-End Developer Professional Certificate",
    "Oracle Certified Professional: MySQL 8.0 Database Developer",
    "MongoDB Associate Developer (Node.js)",
    "Microsoft Azure Fundamentals AZ-900 · Azure AI Fundamentals AI-900",
    "Microsoft Power BI Data Analyst PL-300 · Excel",
    "Google Data Analytics · OCI Generative AI",
  ],
  contactText:
    "I'm looking for Software Development Engineer roles and internships. Whether you have an opportunity or just want to connect, my inbox is open.",
};
